### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by DreamingRaven** [stove-panini/ansible-raid#1]
Hey @stove-panini ,
I was just getting down to start writing my own ansible role for generating lvmraid 10 volumes, then I found yours which looks like it would be significantly more generic and re-usable than my own would be.

However I noticed you did not have a license listed after I took a closer look. Would it be possible to request an inclusion of a license file even if it is just to say that you don't want others to use your work, just to make it clear to people like me who may stumble across it, but want to respect the owners wishes.

P.S apologies for the fork, I only noticed the license was missing after I clicked the button. I will go delete it until I know how you feel about your work.

**Comment by stove-panini** [comment]
No sweat! Glad you can make use of the role :)
